### ISSUE TITLE
Interfaz pdf

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/practica-de-visual-studio-Edwin38H#2]
[UNA INTERFAZ GRAFICA EN VISUAL STUDIO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Edwin38H/files/6209857/UNA.INTERFAZ.GRAFICA.EN.C.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
